WebApplication8/WebApplication8/Controllers/BlogController.cs
using System.Globalization;
using System.Linq;
using System.Web.Mvc;
using WebApplication8.Models;


namespace BirHikayemVar.Controllers
{
    
    
    public class BlogController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        public ActionResult ChangeCulture(string lang, string returnUrl)
        {
            Session["Culture"] = new CultureInfo(lang);
            return Redirect(returnUrl);
        }
        public ActionResult Home1()
        {
            return View(db.Hikayes.ToList());
        }
    }
}

WebApplication8/WebApplication8/Controllers/OtherController.cs
using System.Web.Mvc;


namespace BirHikayemVar.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult FullWidth()
        {
            return View();
        }
        
        public ActionResult SideBar()
        {
            return View();
        }
        
        public ActionResult Faq()
        {
            return View();
        }
        
        public ActionResult FourOhFour()
        {
            return View();
        }
    }
}

WebApplication8/WebApplication8/Views/Other/Faq.cshtml
@{
    ViewBag.Title = @WebApplication8.Resources.lang.ss;
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @WebApplication8.Resources.lang.ss
                <small>@WebApplication8.Resources.lang.ss9</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink(@WebApplication8.Resources.lang.anasayfa, "Home1", "Blog")
                </li>
                <li class="active">@WebApplication8.Resources.lang.ss</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div id="accordion" class="panel-group">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="#collapseOne" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                                @WebApplication8.Resources.lang.ss1
                            </a>
                        </h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapseOne" style="height: 0px;">
                        <div class="panel-body">
                           @WebApplication8.Resources.lang.ss2
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="#collapseTwo" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                                @WebApplication8.Resources.lang.ss3
                            </a>
                        </h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapseTwo" style="height: 0px;">
                        <div class="panel-body">
                               @WebApplication8.Resources.lang.ss4
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="#collapseThree" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                                @WebApplication8.Resources.lang.ss5
                            </a>
                        </h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapseThree">
                        <div class="panel-body">
                            @WebApplication8.Resources.lang.ss6
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a href="#collapseFour" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                                @WebApplication8.Resources.lang.ss7
                            </a>
                        </h4>
                    </div>
                    <div class="panel-collapse collapse" id="collapseFour">
                        <div class="panel-body">
                              @WebApplication8.Resources.lang.ss8
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication8/WebApplication8/Views/Other/FourOhFour.cshtml
@{
    ViewBag.Title = "FAQ";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                404
                <small>Page Not Found</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">404</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p class="error-404">404</p>
            <p class="lead">The page you're looking for could not be found.</p>
            <p>Here are some helpful links to help you find what you're looking for:</p>
            <ul>
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
                <li>
                    <a href="#">Blog</a>
                </li>
                <li>
                    <a href="#">Other</a>
                </li>
            </ul>
        </div>
    </div>
</div>

WebApplication8/WebApplication8/Views/Other/FullWidth.cshtml
@{
    ViewBag.Title = "Full Width Page";
}
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Full Width Page
                <small>For Deeper Customization</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li class="active">Full Width Page</li>
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <p>This page features a page header, breadcrumbs, and the footer but that's it. Use this as a template for completely custom pages you wish to add to your site.</p>
            <p>Be sure to read over and understand all of the Bootstrap 3 components at <a href="http://getbootstrap.com">http://getbootstrap.com</a> to get the most out of any Start Bootstrap template.</p>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam placerat nunc ut tellus tristique, non posuere neque iaculis. Fusce aliquet dui ut felis rhoncus, vitae molestie mauris auctor. Donec pellentesque feugiat leo a adipiscing. Pellentesque quis tristique eros, sed rutrum mauris.</p>
        </div>
    </div>
</div>

WebApplication8/WebApplication8/Views/Other/SideBar.cshtml
@{
    ViewBag.Title = "Sidebar Page";
}
<div class="container">
    <div class="row">
        <div class="col-md-3 col-sm-4 sidebar">
            <ul class="nav nav-stacked nav-pills">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
                <li class="disabled">
                    <a href="#">Portfolio</a>
                </li>
                <li>
                    <a href="#">1 Column Portfolio</a>
                </li>
                <li>
                    <a href="#">2 Column Portfolio</a>
                </li>
                <li>
                    <a href="#">3 Column Portfolio</a>
                </li>
                <li>
                    <a href="#">4 Column Portfolio</a>
                </li>
                <li>
                    <a href="#">Single Portfolio Item</a>
                </li>
                <li class="disabled">
                    <a href="#">Blog</a>
                </li>
                <li>
                    <a href="#">Blog Home 1</a>
                </li>
                <li>
                    <a href="#">Blog Home 2</a>
                </li>
                <li>
                    <a href="#">Blog Post</a>
                </li>
                <li class="disabled">
                    <a href="#">Blog</a>
                </li>
                <li>
                    <a href="#">Full Width Page</a>
                </li>
                <li class="active">
                    <a href="#">Sidebar Page</a>
                </li>
                <li>
                    <a href="#">FAQ</a>
                </li>
                <li>
                    <a href="#">404</a>
                </li>
                <li>
                    <a href="#">Pricing Table</a>
                </li>
            </ul>
        </div>
        <div class="col-md-9 col-sm-8">
            <h1 class="page-header">
                Sidebar Page
                <small>For Deeper Customization</small>
            </h1>
            <ol class="breadcrumb">
                <li>
                    @Html.ActionLink("Home", "Index", "Home")

                </li>
                <li class="active">Sidebar Page</li>
            </ol>
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc placerat diam quis nisl vestibulum dignissim. In hac habitasse platea dictumst. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Etiam placerat nunc ut tellus tristique, non posuere neque iaculis. Fusce aliquet dui ut felis rhoncus, vitae molestie mauris auctor. Donec pellentesque feugiat leo a adipiscing. Pellentesque quis tristique eros, sed rutrum mauris.</p>
        </div>
    </div>
    <!-- /.row -->
</div>