WebApplication8/WebApplication8/Controllers/AboutController.cs
using System.Web.Mvc;

namespace BirHikayemVar.Controllers
{
    public class AboutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication8/WebApplication8/Controllers/ContactController.cs
using System.Web.Mvc;

namespace BirHikayemVar.Controllers
{
    public class ContactController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
	}
}

WebApplication8/WebApplication8/Controllers/OtherController.cs
using System.Web.Mvc;


namespace BirHikayemVar.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult FullWidth()
        {
            return View();
        }
        
        public ActionResult SideBar()
        {
            return View();
        }
        
        public ActionResult Faq()
        {
            return View();
        }
        
        public ActionResult FourOhFour()
        {
            return View();
        }
    }
}

WebApplication8/WebApplication8/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@WebApplication8.Resources.lang.hakkimizda - @ViewBag.Title</title>

    <!-- Bootstrap -->
    <link href="@Url.Content("/css/bootstrap.css")" rel="stylesheet">
    <link href="@Url.Content("/css/modern-business.css")" rel="stylesheet">
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <!-- You'll want to use a responsive image option so this logo looks good on devices - I recommend using something like retina.js (do a quick Google search for it and you'll find it) -->
                @Html.ActionLink(@WebApplication8.Resources.lang.hakkimizda, "Home1", new { controller = "Blog" }, new { @class = "navbar-brand" })
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li id="about">
                       @Html.ActionLink(@WebApplication8.Resources.lang.hakkimizda8, "Index", "About")
                    </li>
                    <!-- <li id="services">
                        @Html.ActionLink("Services", "Index", "Services")
                    </li> 
                         <li id="portfolio" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Portfolio <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="singleportfolioitem">
                                @Html.ActionLink("Single Portfolio Item", "SingleItem", "Portfolio")
                            </li>
                        </ul>
                    </li>
                         <li id="blog" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Blog <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="bloghome1">
                                @Html.ActionLink("Blog Home 1", "Home1", "Blog")
                            </li>
                        </ul>
                    </li>
                        <li id="other" class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Other Pages <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li id="fullwidthpage">
                                @Html.ActionLink("Full Width Page", "FullWidth", "Other")
                            </li>
                            <li id="sidebarpage">
                                @Html.ActionLink("Sidebar Page", "Sidebar", "Other")
                            </li>
                            <li id="faq">
                                @Html.ActionLink("FAQ", "Faq", "Other")
                            </li>
                            <li id="404">
                                @Html.ActionLink("404", "FourOhFour", "Other")
                            </li>
                        </ul>
                    </li>
                     -->
                    <li id="contact">
                        @Html.ActionLink(@WebApplication8.Resources.lang.il1, "Index", "Contact")
                    </li>
                    <li id="faq">
                        @Html.ActionLink(@WebApplication8.Resources.lang.ss, "Faq", "Other")
                    </li>
                    <li>
                        @Html.Partial("_LoginPartial")
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    @RenderBody()

    <div class="container">

        <hr>

        <footer>
            <div class="row">
                <div class="col-lg-12" align="center">
                    <p>@WebApplication8.Resources.lang.copy</p>
                </div>
            </div>
        </footer>

    </div>
    <!-- /.container -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="@Url.Content("/js/bootstrap.js")"></script>
    <script src="@Url.Content("/js/modern-business.js")"></script>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>